name: CD
permissions: write-all
on:
  push:
    branches: [main]

jobs:
  release:
    permissions:
      # Required in order to create releases and tags.
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      # When dogfooding ourselves, target main branch to avoid chasing tags
      - uses: griceturrble/github-actions-cd-action@main
